import type { DesignRecord, Screen } from "./storage";

/**
 * Hand-off payload for an AI coding agent (Claude Code et al). Deliberately a clean,
 * self-describing shape rather than a dump of our internal DesignRecord — the consumer
 * is a model reading JSON cold, so field names carry the meaning.
 */
export type WireframeExport = {
  designTitle: string;
  designMd: string;
  platform: string;
  pwa: boolean;
  screens: {
    id: string;
    name: string;
    platform: "mobile" | "web";
    components: { type: string; label: string; onClick?: string }[];
  }[];
};

export function buildWireframeExport(opts: {
  design: DesignRecord | null;
  idea: string;
  platform: string;
  pwa: boolean;
  designMd: string;
  screens: Screen[];
}): WireframeExport {
  return {
    designTitle: opts.design?.title || opts.idea.slice(0, 60) || "Untitled design",
    designMd: opts.designMd,
    platform: opts.platform,
    pwa: opts.pwa,
    screens: opts.screens.map((s) => ({
      id: s.id,
      name: s.name,
      platform: s.platform,
      // Drop generatedImage: it's a server path, meaningless to whoever unzips this.
      components: s.components.map((c) => ({ type: c.type, label: c.label, ...(c.onClick ? { onClick: c.onClick } : {}) })),
    })),
  };
}

/** Filesystem-safe, stably-ordered name. Index prefix also disambiguates duplicate screen names. */
export function screenFileName(screen: Screen, index: number): string {
  const slug = screen.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "screen";
  return `${String(index + 1).padStart(2, "0")}-${slug}.png`;
}

/** README shipped inside the hi-fi zip so an agent has full context without guessing. */
export function buildHifiReadme(title: string, designMd: string, entries: { name: string; file: string }[]): string {
  const rows = entries.map((e) => `| ${e.name} | \`screens/${e.file}\` |`).join("\n");
  return `# ${title} — hi-fi mockups

Generated by PRD Forge. Screen mockups live in \`screens/\`; the design system spec is
reproduced below and also written to \`DESIGN.md\`.

## Screens

| Screen | File |
| --- | --- |
${rows}

## DESIGN.md

${designMd}
`;
}

/** Never surface a bare record id to the user — fall back to the idea text, then a placeholder. */
export function planLabel(plan: { title?: string; idea?: string }): string {
  return plan.title?.trim() || plan.idea?.trim().slice(0, 60) || "Untitled PRD";
}
