// Blueprint store for the Rancang MCP server.
//
// Blueprints are the finished multi-document output of Rancang (prd/spec/plan/tasks).
// They live as plain JSON files under ~/.rancang/blueprints so that BOTH the
// Next.js app (web) and the MCP server (stdio/HTTP) can read and write the same
// folder without a shared database. Override the root with RANCANG_HOME.
//
// This module is plain ESM JavaScript on purpose: it is imported by the Next.js
// API routes AND executed directly by `node` for the stdio MCP transport, so it
// must not depend on the TypeScript build.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export const DOC_NAMES = ["prd", "spec", "plan", "tasks"];

export function rancangHome() {
  return process.env.RANCANG_HOME || path.join(os.homedir(), ".rancang");
}

export function blueprintDir() {
  return path.join(rancangHome(), "blueprints");
}

function ensureDir() {
  const dir = blueprintDir();
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function newId() {
  const stamp = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 8);
  return `bpl_${stamp}${rand}`;
}

function fileFor(id) {
  // Ids are generated by us; still, refuse anything that could escape the folder.
  const safe = String(id).replace(/[^A-Za-z0-9_-]/g, "");
  if (!safe) throw new Error("invalid blueprint id");
  return path.join(blueprintDir(), `${safe}.json`);
}

export function saveBlueprint(input) {
  const docs = {};
  for (const name of DOC_NAMES) {
    const value = input?.docs?.[name];
    if (typeof value === "string" && value.trim()) docs[name] = value;
  }
  if (Object.keys(docs).length === 0) {
    throw new Error("blueprint needs at least one of: " + DOC_NAMES.join(", "));
  }

  ensureDir();
  const existing = input?.id ? readBlueprint(input.id) : null;
  const record = {
    id: existing?.id || newId(),
    title: (input?.title || existing?.title || docs.prd?.split("\n")[0] || "Untitled blueprint")
      .replace(/^#+\s*/, "")
      .slice(0, 160),
    idea: input?.idea ?? existing?.idea ?? "",
    model: input?.model ?? existing?.model ?? "",
    createdAt: existing?.createdAt ?? Date.now(),
    updatedAt: Date.now(),
    source: input?.source || existing?.source || "web",
    docs: { ...(existing?.docs || {}), ...docs },
  };
  fs.writeFileSync(fileFor(record.id), JSON.stringify(record, null, 2), "utf8");
  return record;
}

export function readBlueprint(id) {
  try {
    return JSON.parse(fs.readFileSync(fileFor(id), "utf8"));
  } catch {
    return null;
  }
}

export function listBlueprints() {
  ensureDir();
  const files = fs.readdirSync(blueprintDir()).filter((f) => f.endsWith(".json"));
  const out = [];
  for (const f of files) {
    try {
      const record = JSON.parse(fs.readFileSync(path.join(blueprintDir(), f), "utf8"));
      out.push({
        id: record.id,
        title: record.title,
        idea: record.idea,
        model: record.model,
        createdAt: record.createdAt,
        updatedAt: record.updatedAt ?? record.createdAt,
        source: record.source,
        docs: DOC_NAMES.filter((d) => record.docs?.[d]),
        tasks: summarizeTasks(record.docs?.tasks || ""),
      });
    } catch {
      // Skip unreadable/partial files rather than failing the whole listing.
    }
  }
  return out.sort((a, b) => (b.updatedAt ?? 0) - (a.updatedAt ?? 0));
}

export function latestBlueprint() {
  return listBlueprints()[0] || null;
}

/** Resolve "latest" / undefined / a full id / a unique id prefix. */
export function resolveBlueprint(idOrPrefix) {
  if (!idOrPrefix || idOrPrefix === "latest") {
    const latest = latestBlueprint();
    return latest ? readBlueprint(latest.id) : null;
  }
  const direct = readBlueprint(idOrPrefix);
  if (direct) return direct;
  const matches = listBlueprints().filter((b) => b.id.startsWith(String(idOrPrefix)));
  if (matches.length === 1) return readBlueprint(matches[0].id);
  return null;
}

// ---------------------------------------------------------------------------
// tasks.md parsing / updating
// ---------------------------------------------------------------------------
// Rancang's tasks.md is generated in the Spec-Kit task format:
//   - [ ] T012 [P] [US1] Create the Thing in src/thing.ts
// We parse those checkbox lines so an agent can pull one task at a time and
// tick it off as it goes, which is what makes the loop resumable.

// Task bullets are not written to one spec. Across five runs of the same model
// on the same prompt we saw five different shapes for the same task:
//   - [ ] T001 Do the thing     checkbox + id   (the template's own shape)
//   - [x] T002 Do the thing     checkbox, ticked
//   - T1 Do the thing           bare id
//   - [T1] Do the thing         id in brackets
//   - **F1** Do the thing       id in bold       (**US1-1** for story-scoped ids)
// Enumerating those spellings was a losing game — each fix just taught us the
// next variant, and every miss reported "0 tasks" silently, which is the worst
// failure mode: the blueprint looked fine and the agent loop sat idle. So
// recognize a task bullet structurally instead of by spelling.
//
// A task bullet is a list marker, then a run of wrappers, then an id token.
// The id is the discriminator: prose bullets never start with one. So peel
// wrappers until we land on the id, then everything after it is the task text.

const LIST_RE = /^(\s*)[-*]\s+(.*)$/;
const CHECKBOX_RE = /^\[\s*([xX]?)\s*\]\s*/;
const BRACKET_RE = /^\[([^\]]*)\]\s*/;
const BOLD_RE = /^\*\*([^*]+)\*\*\s*/;
const TICK_RE = /^`([^`]+)`\s*/;
const ID_RE = /^((?:US|F|T|P|PH|S)?\d+(?:[.-]\d+)*)\b/;

/** True when a token is a bare task id (T001, F1, US1-1, PH2) — not prose. */
function isTaskId(token) {
  if (!token) return false;
  return /^(?:US|F|T|P|PH|S)?\d+(?:[.-]\d+)*$/i.test(token.trim());
}

/** Normalize a task bullet to { mark, id, rest } — or null when the line isn't a task. */
function matchTask(line) {
  const lm = LIST_RE.exec(line);
  if (!lm) return null;

  let s = lm[2].trim();
  let mark = " ";

  // Peel leading wrappers. A wrapper that *contains* the id promotes it to the
  // front; anything else (a [P] priority flag, an [US1] story tag) is dropped.
  for (let guard = 0; guard < 6; guard++) {
    const cb = CHECKBOX_RE.exec(s);
    if (cb) {
      if (cb[1]) mark = "x";
      s = s.slice(cb[0].length);
      continue;
    }
    const br = BRACKET_RE.exec(s);
    if (br) {
      const inner = br[1].trim();
      if (isTaskId(inner)) s = `${inner} ${s.slice(br[0].length)}`;
      else s = s.slice(br[0].length);
      continue;
    }
    const bd = BOLD_RE.exec(s);
    if (bd) {
      const inner = bd[1].trim();
      if (isTaskId(inner)) s = `${inner} ${s.slice(bd[0].length)}`;
      else s = s.slice(bd[0].length);
      continue;
    }
    const bt = TICK_RE.exec(s);
    if (bt) {
      s = s.slice(bt[0].length);
      continue;
    }
    break;
  }

  const idm = ID_RE.exec(s);
  if (!idm) return null;

  // Everything after the id is the task text — but the id may have been
  // followed by more wrappers ([P], [US1], **, backticks) before the prose
  // starts. Strip those, then the separator punctuation, then trim.
  let rest = s.slice(idm[0].length);
  for (let guard = 0; guard < 6; guard++) {
    const next = rest
      .replace(/^\s+/, "")
      .replace(/^\[[^\]]*\]/, "")
      .replace(/^\*\*[^*]*\*\*/, "")
      .replace(/^`[^`]*`/, "");
    if (next === rest) break;
    rest = next;
  }
  rest = rest.replace(/^[\s.:)—\-\]*`\[\]]+/, "").trim();

  return { mark, id: idm[1], rest };
}

export function parseTasks(markdown) {
  if (!markdown) return [];
  const lines = markdown.split("\n");
  const tasks = [];
  let phase = "";
  lines.forEach((line, index) => {
    const heading = line.match(/^#{2,3}\s+(.*)$/);
    if (heading) phase = heading[1].trim();
    const m = matchTask(line);
    if (!m) return;
    const { mark, id, rest } = m;
    tasks.push({
      line: index,
      id: id || `line${index + 1}`,
      done: mark.toLowerCase() === "x",
      phase,
      text: rest.trim(),
    });
  });
  return tasks;
}

export function summarizeTasks(markdown) {
  const tasks = parseTasks(markdown);
  return {
    total: tasks.length,
    done: tasks.filter((t) => t.done).length,
    pending: tasks.filter((t) => !t.done).length,
  };
}

/** Tick a task off (or back on) in the stored tasks.md. Returns the updated task list. */
export function completeTask(idOrPrefix, taskId, done = true) {
  const record = resolveBlueprint(idOrPrefix);
  if (!record) throw new Error(`blueprint not found: ${idOrPrefix ?? "latest"}`);
  if (!record.docs?.tasks) throw new Error("blueprint has no tasks.md");

  const lines = record.docs.tasks.split("\n");
  const wanted = String(taskId).trim().toUpperCase();
  let hit = false;

  const updated = lines.map((line) => {
    const m = matchTask(line);
    if (!m || hit) return line;
    const { id, rest } = m;
    const lineId = (id || "").toUpperCase();
    // Match on the task id (T012) or on an id prefix when the file has none.
    if (lineId !== wanted && !rest.trim().toUpperCase().startsWith(wanted)) return line;
    hit = true;
    // Rewrite as the canonical checkbox shape, so ticking a bare-id task
    // upgrades it in place instead of appending a second representation.
    const indent = line.slice(0, line.search(/\S/));
    return `${indent}- [${done ? "x" : " "}] ${id ? id + " " : ""}${rest}`;
  });

  if (!hit) throw new Error(`task not found in ${record.id}: ${taskId}`);
  record.docs.tasks = updated.join("\n");
  record.updatedAt = Date.now();
  fs.writeFileSync(fileFor(record.id), JSON.stringify(record, null, 2), "utf8");
  return { id: record.id, taskId: wanted, done, tasks: parseTasks(record.docs.tasks) };
}

// ---------------------------------------------------------------------------
// The deliverable: a ready-to-run execution prompt for a coding agent
// ---------------------------------------------------------------------------

export function buildExecutionPrompt(record, options = {}) {
  const docs = record.docs || {};
  const target = options.agent || "an AI coding agent";
  const workdir = options.working_dir || "";
  const parts = [];

  parts.push(`# Execute blueprint: ${record.title}`);
  parts.push("");
  parts.push(
    `You are ${target} working autonomously on a real project. The complete, approved blueprint is below. Build it for real — no placeholders, no stubs, no fabricated output.`
  );
  parts.push("");
  if (workdir) {
    parts.push(`## Working directory`);
    parts.push("");
    parts.push("```");
    parts.push(workdir);
    parts.push("```");
    parts.push("");
  }
  const order = ["prd", "spec", "plan", "tasks"];
  const chosen = Array.isArray(options.include) && options.include.length ? options.include : order;
  const present = order.filter((n) => chosen.includes(n) && docs[n]);

  // The instructions must only reference documents actually inlined below —
  // telling an agent to "read SPEC first" when SPEC was dropped makes it hunt
  // for a file that does not exist.
  const steps = [];
  if (present.includes("spec")) {
    steps.push(
      "Read SPEC first. Its P1 user story is the MVP — it must work standalone before anything else."
    );
  }
  if (present.includes("tasks")) {
    steps.push(
      "Follow TASKS.md in order, top to bottom. Each task is one concrete unit of work; do not skip or batch them."
    );
  }
  if (present.includes("plan")) {
    steps.push(
      "PLAN.md gives the stack, project structure and phases. Follow it unless it contradicts SPEC."
    );
  }
  if (present.includes("prd")) {
    steps.push(
      "PRD.md is the product contract: goals, requirements, data model, and what is explicitly out of scope. Do not build out-of-scope features."
    );
  }
  steps.push(
    "After each task, verify with a real command (build, test, run). Paste the actual output.",
    "If a task is ambiguous or blocked, stop and report the blocker instead of guessing.",
    "Report progress as `[task-id] done — <evidence>` where evidence is a real file path or command output."
  );
  parts.push("## How to work");
  parts.push("");
  steps.forEach((s, i) => parts.push(`${i + 1}. ${s}`));
  parts.push("");

  for (const name of present) {
    parts.push(`## ${name.toUpperCase()}`);
    parts.push("");
    parts.push(docs[name].trim());
    parts.push("");
  }

  if (docs.tasks) {
    const summary = summarizeTasks(docs.tasks);
    parts.push("## Progress tracker");
    parts.push("");
    parts.push(
      `${summary.done}/${summary.total} tasks complete, ${summary.pending} pending. Pull the next one with the \`rancang_next_task\` tool and mark it with \`rancang_task_complete\` as you finish each.`
    );
    parts.push("");
  }

  parts.push("---");
  parts.push("");
  parts.push(
    "Start now. Begin with the Setup tasks, then the Foundational tasks, then the P1 story. Report real output at every step."
  );

  return parts.join("\n");
}

export function nextTask(idOrPrefix) {
  const record = resolveBlueprint(idOrPrefix);
  if (!record) throw new Error(`blueprint not found: ${idOrPrefix ?? "latest"}`);
  const tasks = parseTasks(record.docs?.tasks || "");
  const pending = tasks.filter((t) => !t.done);
  return {
    id: record.id,
    title: record.title,
    summary: summarizeTasks(record.docs?.tasks || ""),
    next: pending[0] || null,
    remaining: pending.slice(0, 10),
  };
}
